name: Publish NuGet Package

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'

      - name: Get the latest Git tag
        id: git_tag
        run: |
          VERSION=$(git describe --tags --abbrev=0)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Pack Mediator.Abstractions
        run: dotnet pack src/Mediator.Abstractions/Mediator.Abstractions.csproj --configuration Release --output ./nupkgs /p:Version=$VERSION

      - name: Pack Mediator
        run: dotnet pack src/Mediator/Mediator.csproj --configuration Release --output ./nupkgs /p:Version=$VERSION

      - name: Publish to NuGet
        run: |
          dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.MEDIADOR_CSHARP_NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
